name: OpenAPI
author: VixikHD
main: happybe\openapi\OpenAPI
description: Public API for people who want help contributing HappyBE
version: 1.0.0
api: 3.0.0

permissions:
  happybe.voter:
    description: Permission for people who voted
    default: op
  happybe.operator:
    default: op
    description: Permissions for Owners, Developers and Admins
    children:
      happybe.moderator:
        default: op
        description: Permissions for Moderators
        children:
          happybe.builder:
            default: op
            description: Permissions for Builders
            children:
              happybe.helper:
                default: op
                description: Permissions for Helpers
                children:
                  happybe.youtube:
                    default: op
                    description: Permissions for people with YOUTUBE rank
                    children:
                      happybe.bedrock:
                        default: op
                        description: Permissions for people with BEDROCK rank
                        children:
                          happybe.mvp.plus:
                            default: op
                            description: Permissions for people with MVP+
                            children:
                              happybe.mvp:
                                default: op
                                description: Permissions for people with MVP rank
                                children:
                                  happybe.vip:
                                    default: op
                                    description: Permissions for people with VIP